# This is the Root pyproject.toml
#
[tool.poetry]
name = "rs"
version = "0.1.0"
description = ""
authors = ["Brad Miller <bonelake@mac.com>"]
license = "MIT"
readme = "README.md"
packages = [
    # These are the components for the author server
    {include = "development"},
    {include = "rsptx/data_extract", from = "components"},
    {include = "rsptx/visualization", from = "components"},
    {include = "rsptx/db", from = "components"},
    {include = "rsptx/forms", from = "components"},
    {include = "rsptx/auth", from = "components"},
    {include = "rsptx/logging", from = "components"},
    {include = "rsptx/response_helpers", from = "components"},
    {include = "rsptx/validation", from = "components"},
    {include = "rsptx/author_server_api", from = "bases"},
    {include = "rsptx/book_server_api", from = "bases"}

]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"
celery = "^5.2.7"
aiofiles = "^0.8.0"
Jinja2 = "^3.0.0"
pytest = "^7.1.2"
redis = "^4.3.4"
requests = "^2.28.1"
uvicorn = "^0.18.2"
pretext = "^1.0.0"
runestone = ">=6.5.0,<7.0"
SQLAlchemy = "^1.4.0"
psycopg2-binary = "^2.9.3"
fastapi-login = "^1.8.2"
myst-parser = "^0.18.0"
sphinx-reredirects = "^0.1.1"
pandas = "^1.0.0"
altair = "^4.2.0"
WTForms = "^3.0.0"
Starlette-WTF = "^0.4.3"
tqdm = "^4.65.0"
# additional for dash server
dash = {extras = ["celery", "diskcache"], version = "^2.7.0"}
dash-bootstrap-components = "^1.2.1"
gunicorn = "^20.1.0"
botocore = "^1.29.87"
python-dateutil = "^2.8.2"
aiosqlite = "^0.18.0"
pyhumps = "^3.8.0"
pydal = "^20221110.1"
bleach = "^6.0.0"
boto3 = "^1.26.88"
multi-await = "^1.0.4"
aioredis = "^2.0.1"
asyncpg = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
